// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_calcul_poids
/*fonction rcpp_calcul_poids : fonction C++ qui calcule les poids*/ 
NumericMatrix rcpp_lissage(NumericVector x_estim,NumericVector y_estim,NumericVector x_pt,NumericVector y_pt,NumericVector rayon,NumericMatrix var, NumericVector taille_int); 

RcppExport SEXP btb_rcpp_lissage(SEXP x_estimSEXP, SEXP y_estimSEXP, SEXP x_ptSEXP, SEXP y_ptSEXP, SEXP rayonSEXP,SEXP varSEXP,SEXP taille_intSEXP  ) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x_estim(x_estimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_estim(y_estimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_pt(x_ptSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_pt(y_ptSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rayon(rayonSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type var(varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taille_int(taille_intSEXP);
    __result = Rcpp::wrap(rcpp_lissage(x_estim, y_estim, x_pt, y_pt, rayon,var,taille_int));
    return __result;
END_RCPP
}

